/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_wastl_rdfdot_render_GraphvizSerializerNative */

#ifndef _Included_net_wastl_rdfdot_render_GraphvizSerializerNative
#define _Included_net_wastl_rdfdot_render_GraphvizSerializerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_wastl_rdfdot_render_GraphvizSerializerNative
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_wastl_rdfdot_render_GraphvizSerializerNative_render
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
